"""The published documents are read by a test, not maintained by goodwill.

Prose rots in a way code does not: nothing runs it. `docs/divergences.md` is
what the README offers as the record of every place this project's reading
differs from the reference's or the standard's, so a sentence in it that has
stopped being true is worse than an absent one — a reader has no way to tell.

Two ways it rotted, both caught by a reviewer rather than by a gate, both
gated here.

The first: a measured number quoted in prose. `docs/agreement.json` is
regenerated by `tools/crossvalidate.py`, and a correction moved it from 115
pairs to 113. The paragraph that made the correction was updated; a section
further down still said two findings fire on fixtures the reference passes,
which was the same number seen from the other side.

The second: a rule id that no longer means what the sentence says. Rows are
written per rule and rules are renamed, retired and rescoped.

What is deliberately *not* gated: whether a sentence's claim about behaviour
is true. No test can read English. What a test can do is refuse to let the
numbers and the names drift, which is how both of today's went wrong.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DOCS = [ROOT / "docs" / "divergences.md", ROOT / "docs" / "scope.md", ROOT / "README.md"]


def prose(path):
    """The document with its fenced code blocks removed: a rule id inside a
    console sample is output, not a claim."""
    return re.sub(r"```.*?```", "", path.read_text("utf-8"), flags=re.S)


#: Every id shape the registry actually uses. `[a-z]?` alone missed `C11.1H`.
RULE_ID = re.compile(r"\b([CMLBRS]\d+(?:\.\d+[A-Za-z]?)?)(?![\w.-])")


def test_the_id_pattern_matches_every_id_there_is():
    """A pattern that cannot spell an id is a gate that skips it, and it skips
    in silence: a document naming `C11.1H`, or naming a `C11.1X` that was never
    a rule, would read as fine either way. Held against the registry rather
    than against a list, so a new shape of id fails here on the day it is
    added."""
    from iirds_validate.registry import all_rules

    unmatched = sorted(rule.id for rule in all_rules()
                       if not RULE_ID.fullmatch(rule.id))
    assert unmatched == [], unmatched


def test_every_rule_id_named_in_the_documents_exists():
    """A row for a rule that was renamed or retired reads as current."""
    from iirds_validate.registry import all_rules

    known = {rule.id for rule in all_rules()}
    # Ids are written in tables and in sentences: C9, M15.7b, L13, B10, R4,
    # S10. Not followed by a hyphen or an underscore, because the reference's
    # fixture names carry the id too -- `M96-1_false.rdf` names no rule.
    #
    # The suffix may be a capital as well as a lower-case letter: C11.1H is a
    # real rule and matched nothing here, so a document naming it -- or naming
    # a `C11.1X` that never existed -- went unread. The test below holds the
    # pattern against the registry, which is where the shapes of the ids are.
    pattern = RULE_ID
    unknown = {}
    for path in DOCS:
        for match in set(pattern.findall(prose(path))):
            if match not in known:
                unknown.setdefault(path.name, set()).add(match)
    assert unknown == {}, unknown


def test_the_agreement_figures_quoted_in_prose_are_the_measured_ones():
    """`docs/agreement.json` is generated; the prose quotes it. A correction
    that moves the file and updates one paragraph leaves the others saying
    what used to be true."""
    agreement = json.loads((ROOT / "docs" / "agreement.json").read_text("utf-8"))
    counts = agreement["counts"]
    pairs = sum(counts.values())
    text = prose(ROOT / "docs" / "divergences.md")

    # The document states the total and several breakdowns of it. The total
    # has to be there and nothing may exceed it: a breakdown larger than the
    # whole is the shape a stale figure takes when the whole shrinks.
    stated = {int(n) for n in re.findall(r"\b(\d+) pairs\b", text)}
    assert stated, "docs/divergences.md no longer states the pair count"
    assert pairs in stated, (
        "docs/agreement.json has %d pairs and docs/divergences.md states %s"
        % (pairs, sorted(stated)))
    assert max(stated) == pairs, (
        "docs/divergences.md states %d pairs, more than the %d measured"
        % (max(stated), pairs))

    for name, number in counts.items():
        quoted = re.findall(r"`%s` (\d+)" % name, text)
        for value in quoted:
            assert int(value) == number, (name, value, number)


def test_no_finding_is_described_as_firing_on_a_passing_fixture():
    """The category that emptied. `extra` is the classifier's name for a
    finding this project reports and the reference does not, and there are
    none; a sentence saying otherwise is the one that went stale."""
    agreement = json.loads((ROOT / "docs" / "agreement.json").read_text("utf-8"))
    extra = [pair for pair, verdict in agreement.get("verdicts", {}).items()
             if verdict == "extra"]
    text = prose(ROOT / "docs" / "divergences.md")
    claims_some = re.search(r"(\w+) findings? fires? on fixtures the reference says should pass",
                            text)
    if extra:
        assert claims_some, "%d extra pairs and the document does not say so" % len(extra)
    else:
        assert claims_some is None or claims_some.group(1).lower() in ("no", "none"), \
            claims_some.group(0)


@pytest.mark.parametrize("path", DOCS, ids=[p.name for p in DOCS])
def test_the_documents_do_not_point_at_files_that_moved(path):
    """A path named in prose is a promise a reader can follow.

    Only this repository's own paths: `docs/divergences.md` also quotes the
    reference tool's source, `src/util/rules.js` and its neighbours, which are
    not here and are not meant to be.
    """
    named = re.findall(r"`((?:docs|tools|tests|shapes|src/iirds)[\w./-]*)`", prose(path))
    missing = sorted({name for name in named
                      if not (ROOT / name).exists() and "*" not in name})
    assert missing == [], missing
