"""The published documents are read by a test, not maintained by goodwill.

Prose rots in a way code does not: nothing runs it. `docs/divergences.md` is
what the README offers as the record of every place this project's reading
differs from the reference's or the standard's, so a sentence in it that has
stopped being true is worse than an absent one — a reader has no way to tell.

Two ways it rotted, both caught by a reviewer rather than by a gate, both
gated here.

The first: a measured number quoted in prose. `docs/agreement.json` is
regenerated by `tools/crossvalidate.py`, and a correction moved it from 115
pairs to 113. The paragraph that made the correction was updated; a section
further down still said two findings fire on fixtures the reference passes,
which was the same number seen from the other side.

The second: a rule id that no longer means what the sentence says. Rows are
written per rule and rules are renamed, retired and rescoped.

What is deliberately *not* gated: whether a sentence's claim about behaviour
is true. No test can read English. What a test can do is refuse to let the
numbers and the names drift, which is how both of today's went wrong.
"""
from __future__ import annotations

import collections
import json
import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
#: Every document that names a rule id, not the three somebody started with.
#: `CHANGELOG.md` names fifty-nine and `shapes/README.md` twenty-nine -- and the
#: second of those is the prose that ships inside the published shapes archive,
#: so a stranger reads it without this repository beside them. Reading three of
#: them left `docs/design.md` citing `M16`, which is not a rule and is not a
#: catalogue id either; the sentence quotes M16.1's text.
DOCS = [ROOT / "docs" / "divergences.md",
        ROOT / "docs" / "scope.md",
        ROOT / "docs" / "design.md",
        ROOT / "README.md",
        ROOT / "CHANGELOG.md",
        ROOT / "SECURITY.md",
        ROOT / "THIRD_PARTY.md",
        ROOT / "shapes" / "README.md"]


def test_every_document_that_names_a_rule_is_read():
    """The list above is a list, so it can fall behind the tree. Any markdown
    that names a rule id has to be in it."""
    import re as _re

    candidates = sorted(ROOT.glob("*.md")) + sorted((ROOT / "docs").glob("*.md")) \
        + sorted((ROOT / "shapes").glob("*.md"))
    for path in candidates:
        text = _re.sub(r"```.*?```", "", path.read_text("utf-8"), flags=_re.S)
        if RULE_ID.search(text):
            assert path in DOCS, "%s names a rule id and nothing reads it" % path.name


def prose(path):
    """The document with its fenced code blocks removed: a rule id inside a
    console sample is output, not a claim."""
    return re.sub(r"```.*?```", "", path.read_text("utf-8"), flags=re.S)


#: Every id shape the registry actually uses. `[a-z]?` alone missed `C11.1H`.
RULE_ID = re.compile(r"\b([CMLBRS]\d+(?:\.\d+[A-Za-z]?)?)(?![\w.-])")


def test_the_id_pattern_matches_every_id_there_is():
    """A pattern that cannot spell an id is a gate that skips it, and it skips
    in silence: a document naming `C11.1H`, or naming a `C11.1X` that was never
    a rule, would read as fine either way. Held against the registry rather
    than against a list, so a new shape of id fails here on the day it is
    added."""
    from iirds_validate.registry import all_rules

    unmatched = sorted(rule.id for rule in all_rules()
                       if not RULE_ID.fullmatch(rule.id))
    assert unmatched == [], unmatched


def test_every_rule_id_named_in_the_documents_exists():
    """A row for a rule that was renamed or retired reads as current."""
    from iirds_validate.registry import all_rules

    known = {rule.id for rule in all_rules()}
    # Ids are written in tables and in sentences: C9, M15.7b, L13, B10, R4,
    # S10. Not followed by a hyphen or an underscore, because the reference's
    # fixture names carry the id too -- `M96-1_false.rdf` names no rule.
    #
    # The suffix may be a capital as well as a lower-case letter: C11.1H is a
    # real rule and matched nothing here, so a document naming it -- or naming
    # a `C11.1X` that never existed -- went unread. The test below holds the
    # pattern against the registry, which is where the shapes of the ids are.
    pattern = RULE_ID
    unknown = {}
    for path in DOCS:
        for match in set(pattern.findall(prose(path))):
            if match not in known:
                unknown.setdefault(path.name, set()).add(match)
    assert unknown == {}, unknown


def test_the_agreement_figures_quoted_in_prose_are_the_measured_ones():
    """`docs/agreement.json` is generated; the prose quotes it. A correction
    that moves the file and updates one paragraph leaves the others saying
    what used to be true."""
    agreement = json.loads((ROOT / "docs" / "agreement.json").read_text("utf-8"))
    counts = agreement["counts"]
    pairs = sum(counts.values())
    text = prose(ROOT / "docs" / "divergences.md")

    # The document states the total and several breakdowns of it. The total
    # has to be there and nothing may exceed it: a breakdown larger than the
    # whole is the shape a stale figure takes when the whole shrinks.
    stated = {int(n) for n in re.findall(r"\b(\d+) pairs\b", text)}
    assert stated, "docs/divergences.md no longer states the pair count"
    assert pairs in stated, (
        "docs/agreement.json has %d pairs and docs/divergences.md states %s"
        % (pairs, sorted(stated)))
    assert max(stated) == pairs, (
        "docs/divergences.md states %d pairs, more than the %d measured"
        % (max(stated), pairs))

    # Every category has to be quoted somewhere, not only checked where it
    # happens to be quoted. A loop over what a pattern found asserts nothing
    # when the pattern finds nothing, and this one reads "`agree` 42" -- so
    # rewriting the sentence as "`agree` accounts for forty-two of them" left
    # three assertions where there had been three and zero of them running,
    # with the total above still matching so the emptying did not show.
    for name, number in counts.items():
        quoted = re.findall(r"`%s`[^\n]*?\b(\d+)\b" % name, text)
        assert quoted, (
            "docs/divergences.md no longer quotes a number for `%s`; it is one of "
            "the figures this file exists to hold" % name)
        for value in quoted:
            assert int(value) == number, (name, value, number)


def test_no_finding_is_described_as_firing_on_a_passing_fixture():
    """The category that emptied. `extra` is the classifier's name for a
    finding this project reports and the reference does not, and there are
    none; a sentence saying otherwise is the one that went stale."""
    agreement = json.loads((ROOT / "docs" / "agreement.json").read_text("utf-8"))
    extra = [pair for pair, verdict in agreement.get("verdicts", {}).items()
             if verdict == "extra"]
    text = prose(ROOT / "docs" / "divergences.md")
    claims_some = re.search(r"(\w+) findings? fires? on fixtures the reference says should pass",
                            text)
    if extra:
        assert claims_some, "%d extra pairs and the document does not say so" % len(extra)
    else:
        assert claims_some is None or claims_some.group(1).lower() in ("no", "none"), \
            claims_some.group(0)


@pytest.mark.parametrize("path", DOCS, ids=[p.name for p in DOCS])
def test_the_documents_do_not_point_at_files_that_moved(path):
    """A path named in prose is a promise a reader can follow.

    Only this repository's own paths: `docs/divergences.md` also quotes the
    reference tool's source, `src/util/rules.js` and its neighbours, which are
    not here and are not meant to be.
    """
    named = re.findall(r"`((?:docs|tools|tests|shapes|src/iirds)[\w./-]*)`", prose(path))
    missing = sorted({name for name in named
                      if not (ROOT / name).exists() and "*" not in name})
    assert missing == [], missing


def test_a_defence_that_names_a_rule_cites_a_test_that_names_it():
    """`SECURITY.md` says, per threat, which rule defends against it and which
    test pins that. The check above asks only that a cited file exists, and
    every one did -- while the file cited for S6 had never mentioned S6. The
    tests that pin it were in `tests/test_silent_pass.py` from the first
    release. A row is a claim about a rule, so every file it cites has to be
    about that rule.

    Every cited file, not one of them: citing the right test beside a wrong
    one is the same mistake with a witness. And a row this cannot read into
    three cells is a row it does not hold, so that is a failure here rather
    than a silent pass -- a pipe inside a backtick is enough to make one.
    """
    rows = [line for line in (ROOT / "SECURITY.md").read_text("utf-8").splitlines()
            if line.startswith("|") and not line.startswith("|---")][1:]
    checked, uncited, unreadable = set(), [], []
    for row in rows:
        cells = [cell.strip() for cell in row.strip().strip("|").split("|")]
        if len(cells) != 3:
            unreadable.append(row[:60])
            continue
        threat, defence, pinned = cells
        cited = re.findall(r"`(tests/[\w./-]+\.py)`", pinned)
        for rule in set(RULE_ID.findall(threat)) | set(RULE_ID.findall(defence)):
            checked.add(rule)
            named_by = [name for name in cited
                        if (ROOT / name).exists()
                        and re.search(r"\b%s\b" % re.escape(rule), (ROOT / name).read_text("utf-8"))]
            if not cited or len(named_by) != len(cited):
                uncited.append((rule, sorted(set(cited) - set(named_by))))
    assert unreadable == [], unreadable
    assert {"S6", "S10"} <= checked, checked
    assert uncited == [], uncited


#: Every figure about the classification, and which count it has to be. The
#: key is the words the number sits in front of, because that is what a reader
#: pairs it with; the value names the file and the key that answers.
#:
#: The first version held only the sum of the table's rows, so two rows could
#: swap values and pass, and it accepted any figure in the summary paragraph
#: that was *some* row -- the right number under the wrong heading, which is
#: exactly the error it had been written to catch. It also could not see "Six
#: pairs name a rule that does not apply", four weeks stale beside a table
#: saying thirteen. Naming the bucket closes all three.
FIGURES = {
    "pairs are cases where the reference does not report": ("silence", "neither"),
    "are gated by a version or variant": ("silence", "gated"),
    "are fixtures nobody can parse": ("silence", "malformed"),
    "are defects that exist only in the XML tree": ("silence", "invisible"),
    "pairs name a rule that does not apply": ("silence", "gated"),
    "mismatched, the": ("silence", "mismatched"),
    "ours and the": ("silence", "ours"),
    "unclassified.": ("silence", "unclassified"),
    "malformed": ("manifest", "malformed_xml"),
    "are not well-formed XML": ("manifest", "malformed_xml"),
    "fixtures are not well-formed XML": ("manifest", "malformed_xml"),
    "fixtures are committed as zero-byte files": ("manifest", "zero_byte"),
}

#: The rows of the table in "Current agreement", keyed by a phrase of the
#: middle cell. A row whose wording moves has to be re-pointed here on purpose.
TABLE_ROWS = {
    "the expected rule fires here": ("agreement", "agree"),
    "the reference's own assertion passes too": ("silence", "neither"),
    "the fixture does not parse": ("silence", "malformed"),
    "gated by version or variant here": ("silence", "gated"),
    "the defect exists only in the XML tree": ("silence", "invisible"),
    "silent — mismatched": ("silence", "mismatched"),
    "labelled **ours**": ("silence", "ours"),
    "**unclassified**": ("silence", "unclassified"),
}

ROW = re.compile(r"^\|\s*\*{0,2}(\d+)\*{0,2}\s*\|([^|]*)\|", re.M)

#: A figure, written where a named one belongs: digits or one of the words
#: below, on its own, with emphasis stripped. What it deliberately refuses to
#: read is anything glued to something else -- `M76`, `iiRDS 1.2`, `1,013`,
#: `Forty-three`. An earlier version took the last alphabetic run and read
#: `Forty-three` as three, which is the failure this gate exists to prevent
#: happening inside it.
FIGURE = re.compile(r"(?:^|[\s(\[])(\d+|[A-Za-z]+)\s*$")

#: Small numbers this document writes as words, where a named figure sits.
#: Read only in front of an anchor above, never swept for.
WORDS = {"one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6,
         "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11,
         "twelve": 12, "thirteen": 13}

#: Words that are plainly a number and are not in the list above, and the
#: shape of a compound (`Forty-three`). Where a named figure belongs these are
#: *refused*, not skipped: skipping them would let a wrong figure through in
#: the one spelling this cannot check, and the document writes every figure
#: above thirteen in digits already. The message says what to write instead.
BIGGER = {"fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen",
          "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty",
          "ninety", "hundred", "thousand", "zero"}
COMPOUND = re.compile(r"(?:^|[\s(\[])([A-Za-z]+)-([A-Za-z]+)\s*$")


def _read(*where):
    return json.loads(ROOT.joinpath(*where).read_text("utf-8"))


def _counts():
    """The three records these figures come from, by the name they answer to.

    Counted from the per-pair verdicts rather than read out of each file's
    `counts` field. The field is written by the same tool and is the obvious
    thing to read, and nothing checks it: `--check` on either tool compares
    `verdicts` and never looks at `counts`, so a hand-edited `counts` moved
    six published figures with both gates green. Counting here needs no field
    to be trustworthy.
    """
    manifest = _read("tests", "corpus", "plusmeta", "MANIFEST.json")["files"]
    return {
        "agreement": collections.Counter(
            _read("docs", "agreement.json")["verdicts"].values()),
        "silence": collections.Counter(
            _read("docs", "silence.json")["verdicts"].values()),
        "manifest": collections.Counter(
            entry["parses"] for entry in manifest.values()),
    }


#: `_figure` says which of three things is in front of an anchor.
NO_FIGURE, UNREADABLE = "no figure", "unreadable figure"


def _figure(said: str):
    """What is written in front of an anchor: a number, nothing, or a refusal.

    `NO_FIGURE` is skipped. A figure separated from its anchor by an aside --
    "13 of the 61 silent pairs are gated by ..." -- is true and unreadable, and
    a gate that refuses a true sentence teaches the next person to work around
    it. One was withdrawn from this file for doing exactly that.

    `UNREADABLE` is not skipped, because it is a number: a word above thirteen
    or a compound. Reading `Forty-three` as its last word gave three, which
    happened to be a real bucket, so a wrong figure passed inside the gate
    written to catch wrong figures.
    """
    said = said.replace("*", "").replace("`", "")
    compound = COMPOUND.search(said)
    if compound and any(part.lower() in WORDS or part.lower() in BIGGER
                        for part in compound.groups()):
        return UNREADABLE
    found = FIGURE.search(said)
    if found is None:
        return NO_FIGURE
    seen = found.group(1).lower()
    if seen.isdigit():
        return int(seen)
    if seen in WORDS:
        return WORDS[seen]
    return UNREADABLE if seen in BIGGER else NO_FIGURE


def test_every_figure_about_the_classification_is_the_measured_one():
    """Six figures under one table had gone stale or had never been right, and
    the gate above them held only the three totals `docs/agreement.json`
    carries. These are tied to the bucket each one is about.

    What this does not hold, said rather than assumed: a figure written in a
    form `_figure` cannot read, and every derived figure in that section --
    "9 pairs over 8 fixtures", "48% of the 61 silent pairs", the per-fixture
    percentages. Those are arithmetic over the buckets rather than a bucket,
    and they want a different mechanism.
    """
    counts = _counts()
    text = prose(ROOT / "docs" / "divergences.md")
    # A longer anchor is here to stop a shorter one reading the noun between
    # the number and itself; it is a disambiguator and not a claim site, so it
    # may be reworded away. Every other anchor has to still be there: one that
    # stops appearing is a figure that stopped being held, quietly.
    disambiguators = {phrase for phrase in FIGURES
                      for other in FIGURES if other != phrase and phrase.endswith(other)}
    missing = [phrase for phrase in FIGURES
               if phrase not in text and phrase not in disambiguators]
    assert not missing, (
        "docs/divergences.md no longer says %s; a figure that moves out from "
        "under its anchor is one nothing holds. Re-point it here on purpose."
        % missing)

    wrong, taken, read = [], set(), 0
    # Longest first: one anchor is a tail of another ("fixtures are not
    # well-formed XML" ends in "are not well-formed XML"), and the shorter one
    # would read the noun between the number and itself as the figure.
    for phrase in sorted(FIGURES, key=len, reverse=True):
        where, key = FIGURES[phrase]
        at = -1
        while True:
            at = text.find(phrase, at + 1)
            if at < 0:
                break
            if at + len(phrase) in taken:
                continue
            taken.add(at + len(phrase))
            said = _figure(text[max(0, at - 40):at])
            if said == NO_FIGURE:
                continue
            if said == UNREADABLE:
                wrong.append((phrase, "a number this gate cannot read; write it "
                                      "in digits", where, key))
                continue
            read += 1
            if said != counts[where].get(key, 0):
                wrong.append((phrase, said, where, key, counts[where].get(key, 0)))
    assert not wrong, wrong
    assert read, "no figure in docs/divergences.md was read; the anchors have moved"


def test_every_row_of_the_silence_table_is_its_own_bucket():
    """Rows are a partition, and a partition is not a sum: the first version of
    this held `sum(rows) == silent`, which two rows swapping values pass.

    Read over the whole document rather than the section, so a copy of the
    table with stale figures somewhere else is held to the same counts.
    """
    counts = _counts()
    rows = ROW.findall(prose(ROOT / "docs" / "divergences.md"))
    matched, wrong = set(), []
    for number, said in rows:
        for phrase, (where, key) in TABLE_ROWS.items():
            if phrase in said:
                matched.add(phrase)
                if int(number) != counts[where].get(key, 0):
                    wrong.append((phrase, int(number), key, counts[where].get(key, 0)))
    assert not wrong, wrong
    assert matched == set(TABLE_ROWS), sorted(set(TABLE_ROWS) - matched)
    # Near-vacuous on a fresh run -- both records are written from one walk of
    # the catalogue -- and not vacuous against a hand-edited file, or against a
    # bucket appearing that no row of the table accounts for.
    silent = sum(counts["silence"].values())
    assert silent == counts["agreement"]["silent"], (silent, counts["agreement"])


#: The packages this project owns. A name under one of these, shown on the
#: front page, is something a reader will type; a name under anything else is
#: somebody else's and not ours to hold.
OURS = ("iirds", "iirds_validate")

#: `iirds_validate.check(...)` in a fenced example. Only the attribute access
#: is read: a bare `import iirds` says nothing a reader can get wrong.
SHOWN = re.compile(r"\b(%s)\.([A-Za-z_][A-Za-z0-9_]*)" % "|".join(OURS))


def test_every_name_the_front_page_shows_can_be_imported():
    """README.md's one Python example is the only place this project documents
    calling it from another program, and nothing ran it.

    `iirds_validate.__init__` resolves its exports lazily through `__getattr__`
    from a table of names to modules, so a module that moves leaves the table
    pointing at nothing and the failure appears where somebody typed what the
    front page showed them.

    Only `README.md`: a snippet in `CHANGELOG.md` may name something a release
    removed, and it is right that it still does.
    """
    from importlib import import_module

    shown = set()
    for block in re.findall(r"```python\n(.*?)```", (ROOT / "README.md").read_text("utf-8"),
                            re.S):
        shown.update(SHOWN.findall(block))
    assert shown, "README.md shows no name from this project's own packages"

    missing = []
    for package, name in sorted(shown):
        module = import_module(package)
        if not hasattr(module, name):
            missing.append("%s.%s" % (package, name))
    assert not missing, (
        "README.md shows %s, and importing gives no such name" % missing)
