"""Rules that differ only by which class they are about.

Generated by tools/propose_class_rules.py from the rule catalogue; edit that
script, not this file. Every class name here was resolved against the bundled
ontology at generation time, and tests/test_schema_tables.py resolves them
again on every run, so a name that stops existing fails the suite instead of
silently matching nothing.

Two shapes, 61 rules:

    MUST_HAVE_IRI      instances of the class must be named, not blank nodes
    NOT_USED_DIRECTLY  the class is an abstract grouping; use a subclass
"""
from __future__ import annotations

from rdflib.namespace import RDF

from ..model import HOV, IIRDS, MACH, SW, Violation, is_named
from ..registry import rule

NAMESPACES = {"IIRDS": IIRDS, "MACH": MACH, "SW": SW, "HOV": HOV}

#: How the specification and the ontology files spell each namespace. The
#: remedy tells an author which element to go and edit, so it has to use the
#: prefix they will see there: six of these classes live in the machinery
#: domain, and <iirds:SparePart> names nothing at all.
PREFIXES = {"IIRDS": "iirds", "MACH": "iirdsMch", "SW": "iirdsSft", "HOV": "iirdsHov"}

#: 61 rules.
MUST_HAVE_IRI = [
    ("M7.1",  "IIRDS", 'InformationObject',               None),
    ("M20.1", "IIRDS", 'IdentityDomain',                  None),
    ("M37",   "IIRDS", 'Document',                        'rdfclasses_core_Document#1'),
    ("M38",   "IIRDS", 'Component',                       'rdfclasses_core_Component#3'),
    ("M39",   "IIRDS", 'Concept',                         'rdfclasses_core_Concept#1'),
    ("M40",   "IIRDS", 'ContentLifeCycleStatusValue',     'rdfclasses_core_ContentLifeCycleStatusValue#1'),
    ("M41",   "IIRDS", 'DirectoryNodeType',               'rdfclasses_core_DirectoryNodeType#1'),
    ("M42",   "IIRDS", 'DocumentType',                    'rdfclasses_core_DocumentType#1'),
    ("M43",   "IIRDS", 'Event',                           'rdfclasses_core_Event#1'),
    ("M44",   "IIRDS", 'Form',                            'rdfclasses_core_Form#1'),
    ("M45",   "IIRDS", 'Formality',                       'rdfclasses_core_Formality#1'),
    ("M46",   "IIRDS", 'Fragment',                        'rdfclasses_core_Fragment#1'),
    ("M47",   "IIRDS", 'Functionality',                   'rdfclasses_core_Functionality#1'),
    ("M48",   "IIRDS", 'IdentityDomain',                  None),
    ("M49",   "IIRDS", 'IdentityType',                    'rdfclasses_core_IdentityType#1'),
    ("M50",   "IIRDS", 'InformationObject',               None),
    ("M51",   "IIRDS", 'Learning',                        'rdfclasses_core_Learning#2'),
    ("M52",   "IIRDS", 'Package',                         'rdfclasses_core_Package#1'),
    ("M53",   "IIRDS", 'Party',                           'rdfclasses_core_Party#2'),
    ("M54",   "IIRDS", 'PartyRole',                       'rdfclasses_core_PartyRole#1'),
    ("M55",   "IIRDS", 'Process',                         'rdfclasses_core_Process#1'),
    ("M56",   "IIRDS", 'ProductFunction',                 'rdfclasses_core_ProductFunction#2'),
    ("M57",   "IIRDS", 'ProductProperty',                 'rdfclasses_core_ProductProperty#1'),
    ("M58",   "IIRDS", 'ProductVariant',                  'rdfclasses_core_ProductVariant#1'),
    ("M59",   "IIRDS", 'Reference',                       'rdfclasses_core_Reference#1'),
    ("M60",   "IIRDS", 'Role',                            'rdfclasses_core_Role#1'),
    ("M61",   "IIRDS", 'Safety',                          'rdfclasses_core_Safety#1'),
    ("M62",   "IIRDS", 'SkillLevel',                      'rdfclasses_core_SkillLevel#2'),
    ("M63",   "IIRDS", 'Supply',                          'rdfclasses_core_Supply#1'),
    ("M64",   "IIRDS", 'Task',                            'rdfclasses_core_Task#3'),
    ("M65",   "IIRDS", 'TechnicalData',                   'rdfclasses_core_TechnicalData#1'),
    ("M66",   "IIRDS", 'TechnicalOverview',               'rdfclasses_core_TechnicalOverview#1'),
    ("M67",   "IIRDS", 'Topic',                           'rdfclasses_core_Topic#1'),
    ("M68",   "IIRDS", 'TopicType',                       'rdfclasses_core_TopicType#2'),
    ("M69",   "IIRDS", 'Troubleshooting',                 'rdfclasses_core_Troubleshooting#1'),
    ("M70",   "IIRDS", 'Use',                             'rdfclasses_core_Use#1'),
    ("M71",   "IIRDS", 'WarningMessage',                  'rdfclasses_core_WarningMessage#1'),
    ("M72",   "MACH", 'ConsumableSupply',                'rdfclasses_machinery_ConsumableSupply#2'),
    ("M73",   "MACH", 'HardwareTool',                    'rdfclasses_machinery_HardwareTool#2'),
    ("M74",   "MACH", 'Lubricant',                       'rdfclasses_machinery_Lubricant#2'),
    ("M75",   "MACH", 'OperatingSupply',                 'rdfclasses_machinery_OperatingSupply#3'),
    ("M76",   "MACH", 'ProtectiveEquipment',             'rdfclasses_machinery_ProtectiveEquipment#3'),
    ("M77",   "MACH", 'SparePart',                       'rdfclasses_machinery_SparePart#2'),
    ("M78",   "IIRDS", 'AfterUse',                        'rdfclasses_core_AfterUse#1'),
    ("M79",   "IIRDS", 'Collection',                      'rdfclasses_core_Collection#1'),
    ("M80",   "IIRDS", 'Conformity',                      'rdfclasses_core_Conformity#1'),
    ("M81",   "IIRDS", 'DesignAndRealization',            'rdfclasses_core_DesignAndRealization#1'),
    ("M82",   "IIRDS", 'DocumentationMetadata',           None),
    ("M83",   "IIRDS", 'FunctionalMetadata',              None),
    ("M84",   "IIRDS", 'iirdsDomainEntity',               None),
    ("M85",   "IIRDS", 'AdministrativeMetadata',          None),
    ("M86",   "IIRDS", 'InformationSubject',              'rdfclasses_core_InformationSubject#1'),
    ("M87",   "IIRDS", 'InformationType',                 'rdfclasses_core_InformationType#1'),
    ("M88",   "IIRDS", 'PlanningTime',                    None),
    ("M89",   "IIRDS", 'ProductFeature',                  'rdfclasses_core_ProductFeature#1'),
    ("M90",   "IIRDS", 'ProductLifeCyclePhase',           'rdfclasses_core_ProductLifeCyclePhase#1'),
    ("M91",   "IIRDS", 'ProductMetadata',                 'rdfclasses_core_ProductMetadata#1'),
    ("M92",   "IIRDS", 'PuttingToUse',                    'rdfclasses_core_PuttingToUse#1'),
    ("M93",   "IIRDS", 'Qualification',                   'rdfclasses_core_Qualification#1'),
    ("M97.1", "IIRDS", 'ClassificationDomain',            None),
    ("M97.2", "IIRDS", 'ClassificationDomain',            None),
]
#: 0 rules.
NOT_USED_DIRECTLY = [
]


def _must_have_iri(prefix: str, class_name: str):
    """Instances of this class must be named by an absolute IRI."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        # How far this rule reaches is decided by what the ontology says about
        # the class, not by the shape of the table.
        #
        # Where Appendix A states "IRI: required", section 7 applies: a package
        # may subclass the class, a consumer must process the instance as the
        # parent, and the standard asks that instance for an IRI. Exact typing
        # there sees a smaller population than the standard gives, and a
        # smaller one than the rule's own shape, whose sh:targetClass follows
        # the data graph's rdfs:subClassOf.
        #
        # Where the ontology asks for no IRI — ten of these classes say nothing
        # about one, and iirds:PlanningTime says "IRI: optional" — the rule is
        # here because the reference tool asserts that elements of the class
        # carry rdf:about. That tool reads the XML tree, so the population it
        # can see is what is typed with the class itself, and reaching past it
        # would report the extension section 7 exists to allow: two packages
        # differing only in whether an anonymous node is typed with the
        # standard's own subclass or the package's, one passing and one not.
        #
        # The ontology's own hierarchy stays out either way: iirdsDomainEntity
        # sits above nearly everything, and pulling its descendants in would
        # report every blank-node Rendition in a good package.
        reach = ctx.typed_as if ctx.ontology.requires_an_iri(cls) else ctx.typed_exactly
        for subject in reach(cls):
            if not is_named(subject):
                yield Violation("instances of %s must have an absolute IRI" % class_name,
                                subject=ctx.ref(subject))
    return check


def _not_used_directly(prefix: str, class_name: str):
    """An abstract grouping class: type instances as one of its subclasses."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.graph.subjects(RDF.type, cls):
            yield Violation("%s is not intended to be used directly; "
                            "use one of its subclasses" % class_name,
                            subject=ctx.ref(subject))
    return check


#: The remedy is the same shape for all sixty-one, because the defect is: the
#: element was written without an identifier, so nothing else in the package —
#: or in the package that references this one — can point at it.
NAMED_FIX = ('Give the <%(prefix)s:%(cls)s> element an rdf:about with an IRI, for example '
             'rdf:about="urn:uuid:..." or a URL under a domain you control. Without '
             'one the element is anonymous, so no other statement can refer to it '
             'and a consumer merging this package with another cannot tell two of '
             'them apart.')

ABSTRACT_FIX = ('Retype the instance as one of the subclasses of %(prefix)s:%(cls)s. The '
                'grouping class says only that something of that family is involved, '
                'which leaves a consumer nothing to act on.')


#: Rules whose class the catalogue dates earlier than the vocabulary does.
#:
#: `tools/version_inventory.py` compares each rule's declared versions against
#: the terms that version's ontology actually carried. M97.1/2 name
#: iirds:ClassificationDomain, which arrives in 1.2 with the external
#: classification vocabulary; M49 names iirds:IdentityType and M76
#: mch:ProtectiveEquipment, both of which arrive in 1.1 — settled against the
#: Consortium's own published schemas for every edition, 1.0 included. A rule cannot apply before the class it is about exists.
NARROWED = {
    "M49":   ("1.1", "1.2", "1.3"),
    "M76":   ("1.1", "1.2", "1.3"),
    "M97.1": ("1.2", "1.3"),
    "M97.2": ("1.2", "1.3"),
}


def _register() -> None:
    for rule_id, prefix, class_name, requirement in MUST_HAVE_IRI:
        fn = _must_have_iri(prefix, class_name)
        fn.__name__ = "%s_%s_must_have_iri" % (rule_id.replace(".", "_").lower(), class_name.lower())
        # Always the generated sentence, never the catalogue cell. The cells
        # are either the bare table fragment "IRI: REQUIRED" or -- for
        # M78-M94 -- the ontology's own description prose ("Not intended to
        # be used directly..."), which as a message tells the reader about a
        # different rule than the one firing, and as shipped text contradicts
        # every "no ontology content" notice in shapes/. The constraint is
        # identical for every row, so one accurate sentence covers them all.
        rule(rule_id, versions=NARROWED.get(rule_id),
             covers=(requirement,) if requirement else (),
             title="instances of %s must have an IRI" % class_name,
             fix=NAMED_FIX % {"prefix": PREFIXES[prefix], "cls": class_name})(fn)

    for rule_id, prefix, class_name in NOT_USED_DIRECTLY:
        fn = _not_used_directly(prefix, class_name)
        fn.__name__ = "%s_%s_not_direct" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id, fix=ABSTRACT_FIX % {"prefix": PREFIXES[prefix],
                                          "cls": class_name})(fn)


_register()
