"""Rules that differ only by which class they are about.

Generated by tools/propose_class_rules.py from the rule catalogue; edit that
script, not this file. Every class name here was resolved against the bundled
ontology at generation time, and tests/test_schema_tables.py resolves them
again on every run, so a name that stops existing fails the suite instead of
silently matching nothing.

Two shapes, 58 rules:

    MUST_HAVE_IRI      instances of the class must be named, not blank nodes
    NOT_USED_DIRECTLY  the class is an abstract grouping; use a subclass
"""
from __future__ import annotations

from rdflib import BNode
from rdflib.namespace import RDF

from ..model import HOV, IIRDS, MACH, SW, Violation, is_absolute_iri
from ..registry import rule

NAMESPACES = {"IIRDS": IIRDS, "MACH": MACH, "SW": SW, "HOV": HOV}

#: 42 rules.
MUST_HAVE_IRI = [
    ("M37",   "IIRDS", 'Document'),
    ("M38",   "IIRDS", 'Component'),
    ("M39",   "IIRDS", 'Concept'),
    ("M40",   "IIRDS", 'ContentLifeCycleStatusValue'),
    ("M41",   "IIRDS", 'DirectoryNodeType'),
    ("M42",   "IIRDS", 'DocumentType'),
    ("M43",   "IIRDS", 'Event'),
    ("M44",   "IIRDS", 'Form'),
    ("M45",   "IIRDS", 'Formality'),
    ("M46",   "IIRDS", 'Fragment'),
    ("M47",   "IIRDS", 'Functionality'),
    ("M48",   "IIRDS", 'IdentityDomain'),
    ("M49",   "IIRDS", 'IdentityType'),
    ("M50",   "IIRDS", 'InformationObject'),
    ("M51",   "IIRDS", 'Learning'),
    ("M52",   "IIRDS", 'Package'),
    ("M53",   "IIRDS", 'Party'),
    ("M54",   "IIRDS", 'PartyRole'),
    ("M55",   "IIRDS", 'Process'),
    ("M56",   "IIRDS", 'ProductFunction'),
    ("M57",   "IIRDS", 'ProductProperty'),
    ("M58",   "IIRDS", 'ProductVariant'),
    ("M59",   "IIRDS", 'Reference'),
    ("M60",   "IIRDS", 'Role'),
    ("M61",   "IIRDS", 'Safety'),
    ("M62",   "IIRDS", 'SkillLevel'),
    ("M63",   "IIRDS", 'Supply'),
    ("M64",   "IIRDS", 'Task'),
    ("M65",   "IIRDS", 'TechnicalData'),
    ("M66",   "IIRDS", 'TechnicalOverview'),
    ("M67",   "IIRDS", 'Topic'),
    ("M68",   "IIRDS", 'TopicType'),
    ("M69",   "IIRDS", 'Troubleshooting'),
    ("M70",   "IIRDS", 'Use'),
    ("M71",   "IIRDS", 'WarningMessage'),
    ("M72",   "MACH", 'ConsumableSupply'),
    ("M73",   "MACH", 'HardwareTool'),
    ("M74",   "MACH", 'Lubricant'),
    ("M75",   "MACH", 'OperatingSupply'),
    ("M76",   "MACH", 'ProtectiveEquipment'),
    ("M77",   "MACH", 'SparePart'),
    ("M97.1", "IIRDS", 'ClassificationDomain'),
]
#: 16 rules.
NOT_USED_DIRECTLY = [
    ("M78", "IIRDS", 'AfterUse'),
    ("M79", "IIRDS", 'Collection'),
    ("M80", "IIRDS", 'Conformity'),
    ("M81", "IIRDS", 'DesignAndRealization'),
    ("M82", "IIRDS", 'DocumentationMetadata'),
    ("M83", "IIRDS", 'FunctionalMetadata'),
    ("M84", "IIRDS", 'iirdsDomainEntity'),
    ("M85", "IIRDS", 'AdministrativeMetadata'),
    ("M86", "IIRDS", 'InformationSubject'),
    ("M87", "IIRDS", 'InformationType'),
    ("M88", "IIRDS", 'PlanningTime'),
    ("M89", "IIRDS", 'ProductFeature'),
    ("M90", "IIRDS", 'ProductLifeCyclePhase'),
    ("M91", "IIRDS", 'ProductMetadata'),
    ("M92", "IIRDS", 'PuttingToUse'),
    ("M93", "IIRDS", 'Qualification'),
]


def _must_have_iri(prefix: str, class_name: str):
    """Instances of this class must be named by an absolute IRI."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.instances_of(cls):
            if isinstance(subject, BNode) or not is_absolute_iri(subject):
                yield Violation("instances of %s must have an absolute IRI" % class_name,
                                subject=str(subject))
    return check


def _not_used_directly(prefix: str, class_name: str):
    """An abstract grouping class: type instances as one of its subclasses."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.graph.subjects(RDF.type, cls):
            yield Violation("%s is not intended to be used directly; "
                            "use one of its subclasses" % class_name,
                            subject=str(subject))
    return check


def _register() -> None:
    for rule_id, prefix, class_name in MUST_HAVE_IRI:
        fn = _must_have_iri(prefix, class_name)
        fn.__name__ = "%s_%s_must_have_iri" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id)(fn)

    for rule_id, prefix, class_name in NOT_USED_DIRECTLY:
        fn = _not_used_directly(prefix, class_name)
        fn.__name__ = "%s_%s_not_direct" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id)(fn)


_register()
