"""Rules that differ only by which class they are about.

Generated by tools/propose_class_rules.py from the rule catalogue; edit that
script, not this file. Every class name here was resolved against the bundled
ontology at generation time, and tests/test_schema_tables.py resolves them
again on every run, so a name that stops existing fails the suite instead of
silently matching nothing.

Two shapes, 61 rules:

    MUST_HAVE_IRI      instances of the class must be named, not blank nodes
    NOT_USED_DIRECTLY  the class is an abstract grouping; use a subclass
"""
from __future__ import annotations

from rdflib.namespace import RDF

from ..model import HOV, IIRDS, MACH, SW, Violation, is_named
from ..registry import rule

NAMESPACES = {"IIRDS": IIRDS, "MACH": MACH, "SW": SW, "HOV": HOV}

#: 61 rules.
MUST_HAVE_IRI = [
    ("M7.1",  "IIRDS", 'InformationObject'),
    ("M20.1", "IIRDS", 'IdentityDomain'),
    ("M37",   "IIRDS", 'Document'),
    ("M38",   "IIRDS", 'Component'),
    ("M39",   "IIRDS", 'Concept'),
    ("M40",   "IIRDS", 'ContentLifeCycleStatusValue'),
    ("M41",   "IIRDS", 'DirectoryNodeType'),
    ("M42",   "IIRDS", 'DocumentType'),
    ("M43",   "IIRDS", 'Event'),
    ("M44",   "IIRDS", 'Form'),
    ("M45",   "IIRDS", 'Formality'),
    ("M46",   "IIRDS", 'Fragment'),
    ("M47",   "IIRDS", 'Functionality'),
    ("M48",   "IIRDS", 'IdentityDomain'),
    ("M49",   "IIRDS", 'IdentityType'),
    ("M50",   "IIRDS", 'InformationObject'),
    ("M51",   "IIRDS", 'Learning'),
    ("M52",   "IIRDS", 'Package'),
    ("M53",   "IIRDS", 'Party'),
    ("M54",   "IIRDS", 'PartyRole'),
    ("M55",   "IIRDS", 'Process'),
    ("M56",   "IIRDS", 'ProductFunction'),
    ("M57",   "IIRDS", 'ProductProperty'),
    ("M58",   "IIRDS", 'ProductVariant'),
    ("M59",   "IIRDS", 'Reference'),
    ("M60",   "IIRDS", 'Role'),
    ("M61",   "IIRDS", 'Safety'),
    ("M62",   "IIRDS", 'SkillLevel'),
    ("M63",   "IIRDS", 'Supply'),
    ("M64",   "IIRDS", 'Task'),
    ("M65",   "IIRDS", 'TechnicalData'),
    ("M66",   "IIRDS", 'TechnicalOverview'),
    ("M67",   "IIRDS", 'Topic'),
    ("M68",   "IIRDS", 'TopicType'),
    ("M69",   "IIRDS", 'Troubleshooting'),
    ("M70",   "IIRDS", 'Use'),
    ("M71",   "IIRDS", 'WarningMessage'),
    ("M72",   "MACH", 'ConsumableSupply'),
    ("M73",   "MACH", 'HardwareTool'),
    ("M74",   "MACH", 'Lubricant'),
    ("M75",   "MACH", 'OperatingSupply'),
    ("M76",   "MACH", 'ProtectiveEquipment'),
    ("M77",   "MACH", 'SparePart'),
    ("M78",   "IIRDS", 'AfterUse'),
    ("M79",   "IIRDS", 'Collection'),
    ("M80",   "IIRDS", 'Conformity'),
    ("M81",   "IIRDS", 'DesignAndRealization'),
    ("M82",   "IIRDS", 'DocumentationMetadata'),
    ("M83",   "IIRDS", 'FunctionalMetadata'),
    ("M84",   "IIRDS", 'iirdsDomainEntity'),
    ("M85",   "IIRDS", 'AdministrativeMetadata'),
    ("M86",   "IIRDS", 'InformationSubject'),
    ("M87",   "IIRDS", 'InformationType'),
    ("M88",   "IIRDS", 'PlanningTime'),
    ("M89",   "IIRDS", 'ProductFeature'),
    ("M90",   "IIRDS", 'ProductLifeCyclePhase'),
    ("M91",   "IIRDS", 'ProductMetadata'),
    ("M92",   "IIRDS", 'PuttingToUse'),
    ("M93",   "IIRDS", 'Qualification'),
    ("M97.1", "IIRDS", 'ClassificationDomain'),
    ("M97.2", "IIRDS", 'ClassificationDomain'),
]
#: 0 rules.
NOT_USED_DIRECTLY = [
]


def _must_have_iri(prefix: str, class_name: str):
    """Instances of this class must be named by an absolute IRI."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        # Direct typing only. Expanding to subclasses would make a rule about a
        # grouping class fire on every descendant — iirdsDomainEntity sits above
        # nearly everything, so its rule would report every blank-node Rendition
        # in a perfectly good package. Each class's own rule covers its own
        # instances, and M2.1 covers information units generally.
        for subject in ctx.typed_exactly(cls):
            if not is_named(subject):
                yield Violation("instances of %s must have an absolute IRI" % class_name,
                                subject=ctx.ref(subject))
    return check


def _not_used_directly(prefix: str, class_name: str):
    """An abstract grouping class: type instances as one of its subclasses."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.graph.subjects(RDF.type, cls):
            yield Violation("%s is not intended to be used directly; "
                            "use one of its subclasses" % class_name,
                            subject=ctx.ref(subject))
    return check


#: The remedy is the same shape for all sixty-one, because the defect is: the
#: element was written without an identifier, so nothing else in the package —
#: or in the package that references this one — can point at it.
NAMED_FIX = ('Give the <iirds:%(cls)s> element an rdf:about with an IRI, for example '
             'rdf:about="urn:uuid:..." or a URL under a domain you control. Without '
             'one the element is anonymous, so no other statement can refer to it '
             'and a consumer merging this package with another cannot tell two of '
             'them apart.')

ABSTRACT_FIX = ('Retype the instance as one of the subclasses of iirds:%(cls)s. The '
                'grouping class says only that something of that family is involved, '
                'which leaves a consumer nothing to act on.')


#: Rules whose class the catalogue dates earlier than the vocabulary does.
#:
#: `tools/version_inventory.py` compares each rule's declared versions against
#: the terms that version's ontology actually carried. M97.1/2 name
#: iirds:ClassificationDomain, which arrives in 1.2 with the external
#: classification vocabulary; M49 names iirds:IdentityType and M76
#: mch:ProtectiveEquipment, both of which arrive in 1.1 — settled against the
#: Consortium's own published schemas for every edition, 1.0 included. A rule cannot apply before the class it is about exists.
NARROWED = {
    "M49":   ("1.1", "1.2", "1.3"),
    "M76":   ("1.1", "1.2", "1.3"),
    "M97.1": ("1.2", "1.3"),
    "M97.2": ("1.2", "1.3"),
}


def _register() -> None:
    for rule_id, prefix, class_name in MUST_HAVE_IRI:
        fn = _must_have_iri(prefix, class_name)
        fn.__name__ = "%s_%s_must_have_iri" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id, versions=NARROWED.get(rule_id),
             fix=NAMED_FIX % {"cls": class_name})(fn)

    for rule_id, prefix, class_name in NOT_USED_DIRECTLY:
        fn = _not_used_directly(prefix, class_name)
        fn.__name__ = "%s_%s_not_direct" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id, fix=ABSTRACT_FIX % {"cls": class_name})(fn)


_register()
