#!/usr/bin/env python3
"""Generate the two rule tables whose rows differ only by a class name.

Fifty-nine catalogued rules say one of exactly two things:

    "IRI: REQUIRED"                        — instances of C must have an IRI
    "Not intended to be used directly."    — C must not be typed directly

and the class each one is about is already machine-readable in the catalogue's
`path` field. Writing them out by hand would be fifty-nine copies of a two-line
function; interpreting `path` at run time would be worse, because the catalogue
is someone else's free text and contains typos ("intented"), German editorial
notes and inconsistent casing. So: resolve once, review the result, check the
table in, and keep the generator for the next upstream release.

Every proposed class is resolved against the bundled ontology before it is
emitted. A `path` that does not name a real class is reported and skipped, not
guessed at.

    python tools/propose_class_rules.py            # write the module
    python tools/propose_class_rules.py --check    # fail if it would change
    python tools/propose_class_rules.py --stdout   # just look at it
"""
from __future__ import annotations

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rdflib.namespace import RDF, RDFS  # noqa: E402

from iirds_validate.model import HOV, IIRDS, MACH, SW  # noqa: E402
from iirds_validate.ontology import load  # noqa: E402
from iirds_validate.registry import CATALOG  # noqa: E402

OUT = ROOT / "src/iirds_validate/rules/schema_tables.py"

#: The domain ontologies define classes too — M72 to M77 are machinery terms,
#: not core ones — so a bare class name has to be resolved against all of them.
NAMESPACES = (("IIRDS", IIRDS), ("MACH", MACH), ("SW", SW), ("HOV", HOV))

#: Catalogue `category` values, normalised, and the table each maps to.
FAMILIES = {
    "must have iri": "MUST_HAVE_IRI",
    "not intended to be used directly.": "NOT_USED_DIRECTLY",
    "not intented to be used directly.": "NOT_USED_DIRECTLY",
}

HEADER = '''"""Rules that differ only by which class they are about.

Generated by tools/propose_class_rules.py from the rule catalogue; edit that
script, not this file. Every class name here was resolved against the bundled
ontology at generation time, and tests/test_schema_tables.py resolves them
again on every run, so a name that stops existing fails the suite instead of
silently matching nothing.

Two shapes, {count} rules:

    MUST_HAVE_IRI      instances of the class must be named, not blank nodes
    NOT_USED_DIRECTLY  the class is an abstract grouping; use a subclass
"""
from __future__ import annotations

from rdflib import BNode
from rdflib.namespace import RDF

from ..model import HOV, IIRDS, MACH, SW, Violation, is_absolute_iri
from ..registry import rule

NAMESPACES = {"IIRDS": IIRDS, "MACH": MACH, "SW": SW, "HOV": HOV}

'''

BODY = '''

def _must_have_iri(prefix: str, class_name: str):
    """Instances of this class must be named by an absolute IRI."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.instances_of(cls):
            if isinstance(subject, BNode) or not is_absolute_iri(subject):
                yield Violation("instances of %s must have an absolute IRI" % class_name,
                                subject=str(subject))
    return check


def _not_used_directly(prefix: str, class_name: str):
    """An abstract grouping class: type instances as one of its subclasses."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.graph.subjects(RDF.type, cls):
            yield Violation("%s is not intended to be used directly; "
                            "use one of its subclasses" % class_name,
                            subject=str(subject))
    return check


def _register() -> None:
    for rule_id, prefix, class_name in MUST_HAVE_IRI:
        fn = _must_have_iri(prefix, class_name)
        fn.__name__ = "%s_%s_must_have_iri" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id)(fn)

    for rule_id, prefix, class_name in NOT_USED_DIRECTLY:
        fn = _not_used_directly(prefix, class_name)
        fn.__name__ = "%s_%s_not_direct" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id)(fn)


_register()
'''


def sort_key(rule_id: str):
    head = rule_id[0]
    rest = rule_id[1:]
    parts = rest.split(".")
    out = []
    for part in parts:
        digits = "".join(c for c in part if c.isdigit())
        out.append((int(digits) if digits else 0, part))
    return (head, out)


def collect(ontology):
    tables = {"MUST_HAVE_IRI": [], "NOT_USED_DIRECTLY": []}
    skipped = []

    for rule_id, meta in CATALOG.items():
        family = FAMILIES.get((meta.get("category") or "").strip().lower())
        if family is None:
            continue
        path = (meta.get("path") or "").strip()
        if not path or "," in path or " " in path:
            skipped.append((rule_id, path, "path is not a single class name"))
            continue
        found = [(prefix, ns[path]) for prefix, ns in NAMESPACES
                 if (ns[path], RDF.type, RDFS.Class) in ontology.graph]
        if not found:
            skipped.append((rule_id, path, "not a class in any bundled ontology"))
            continue
        if len(found) > 1:
            skipped.append((rule_id, path, "ambiguous: defined in %s"
                            % ", ".join(p for p, _ in found)))
            continue
        prefix, _iri = found[0]
        tables[family].append((rule_id, prefix, path))

    for rows in tables.values():
        rows.sort(key=lambda row: sort_key(row[0]))
    return tables, skipped


def render(tables) -> str:
    count = sum(len(rows) for rows in tables.values())
    out = [HEADER.replace("{count}", str(count))]
    for name in ("MUST_HAVE_IRI", "NOT_USED_DIRECTLY"):
        rows = tables[name]
        out.append("#: %d rules.\n%s = [\n" % (len(rows), name))
        width = max((len(r[0]) for r in rows), default=0) + 3
        for rule_id, prefix, class_name in rows:
            out.append('    (%s %-7s %r),\n'
                       % (('"%s",' % rule_id).ljust(width), '"%s",' % prefix, class_name))
        out.append("]\n")
    out.append(BODY)
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the file would change")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    tables, skipped = collect(load())
    text = render(tables)

    for rule_id, path, why in sorted(skipped, key=lambda s: sort_key(s[0])):
        print("skipped %-8s path=%-34r %s" % (rule_id, path, why), file=sys.stderr)

    if args.stdout:
        print(text)
        return 0
    if args.check:
        current = OUT.read_text("utf-8") if OUT.exists() else ""
        if current == text:
            print("schema_tables.py is up to date")
            return 0
        print("schema_tables.py is out of date; rerun without --check", file=sys.stderr)
        return 1

    OUT.write_text(text, "utf-8")
    for name, rows in tables.items():
        print("%-18s %3d rules" % (name, len(rows)))
    print("wrote %s" % OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
