#!/usr/bin/env python3
"""Generate the two rule tables whose rows differ only by a class name.

Fifty-nine catalogued rules say one of exactly two things:

    "IRI: REQUIRED"                        — instances of C must have an IRI
    "Not intended to be used directly."    — C must not be typed directly

and the class each one is about is already machine-readable in the catalogue's
`path` field. Writing them out by hand would be fifty-nine copies of a two-line
function; interpreting `path` at run time would be worse, because the catalogue
is someone else's free text and contains typos ("intented"), German editorial
notes and inconsistent casing. So: resolve once, review the result, check the
table in, and keep the generator for the next upstream release.

Every proposed class is resolved against the bundled ontology before it is
emitted. A `path` that does not name a real class is reported and skipped, not
guessed at.

    python tools/propose_class_rules.py            # write the module
    python tools/propose_class_rules.py --check    # fail if it would change
    python tools/propose_class_rules.py --stdout   # just look at it
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from rdflib.namespace import RDF, RDFS  # noqa: E402

from iirds_validate.model import HOV, IIRDS, MACH, SW  # noqa: E402
from iirds_validate.ontology import load  # noqa: E402
from iirds_validate.registry import CATALOG  # noqa: E402

OUT = ROOT / "src/iirds_validate/rules/schema_tables.py"

#: The domain ontologies define classes too — M72 to M77 are machinery terms,
#: not core ones — so a bare class name has to be resolved against all of them.
NAMESPACES = (("IIRDS", IIRDS), ("MACH", MACH), ("SW", SW), ("HOV", HOV))

#: Catalogue `category` values, normalised, and the table each maps to.
#: The catalogue's `category` for M78 to M93 reads "Not intended to be used
#: directly", but the reference tool's assertion for all sixteen is
#:
#:     els.filter(el => !el.hasAttribute("rdf:about")).length === 0
#:
#: which is a must-have-IRI check, not a must-not-be-typed-directly check. Only
#: M1, M12 and M94 in that category actually test for direct use, and those are
#: written by hand. Following the label rather than the implementation made
#: this project report findings on tekom's own sample packages that no other
#: tool reports — so the catalogued ids follow the reference, and the stricter
#: reading of the wording lives in L10, where it is labelled as ours.
FAMILIES = {
    "must have iri": "MUST_HAVE_IRI",
    "absolute iri": "MUST_HAVE_IRI",
    "not intended to be used directly.": "MUST_HAVE_IRI",
    "not intented to be used directly.": "MUST_HAVE_IRI",
}

HEADER = '''"""Rules that differ only by which class they are about.

Generated by tools/propose_class_rules.py from the rule catalogue; edit that
script, not this file. Every class name here was resolved against the bundled
ontology at generation time, and tests/test_schema_tables.py resolves them
again on every run, so a name that stops existing fails the suite instead of
silently matching nothing.

Two shapes, {count} rules:

    MUST_HAVE_IRI      instances of the class must be named, not blank nodes
    NOT_USED_DIRECTLY  the class is an abstract grouping; use a subclass
"""
from __future__ import annotations

from rdflib.namespace import RDF

from ..model import HOV, IIRDS, MACH, SW, Violation, is_named
from ..registry import rule

NAMESPACES = {"IIRDS": IIRDS, "MACH": MACH, "SW": SW, "HOV": HOV}

#: How the specification and the ontology files spell each namespace. The
#: remedy tells an author which element to go and edit, so it has to use the
#: prefix they will see there: six of these classes live in the machinery
#: domain, and <iirds:SparePart> names nothing at all.
PREFIXES = {"IIRDS": "iirds", "MACH": "iirdsMch", "SW": "iirdsSft", "HOV": "iirdsHov"}

'''

BODY = '''

def _must_have_iri(prefix: str, class_name: str):
    """Instances of this class must be named by an absolute IRI."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        # How far this rule reaches is decided by what the ontology says about
        # the class, not by the shape of the table.
        #
        # Where Appendix A states "IRI: required", section 7 applies: a package
        # may subclass the class, a consumer must process the instance as the
        # parent, and the standard asks that instance for an IRI. Exact typing
        # there sees a smaller population than the standard gives, and a
        # smaller one than the rule's own shape, whose sh:targetClass follows
        # the data graph's rdfs:subClassOf.
        #
        # Where the ontology asks for no IRI — ten of these classes say nothing
        # about one, and iirds:PlanningTime says "IRI: optional" — the rule is
        # here because the reference tool asserts that elements of the class
        # carry rdf:about. That tool reads the XML tree, so the population it
        # can see is what is typed with the class itself, and reaching past it
        # would report the extension section 7 exists to allow: two packages
        # differing only in whether an anonymous node is typed with the
        # standard's own subclass or the package's, one passing and one not.
        #
        # The ontology's own hierarchy stays out either way: iirdsDomainEntity
        # sits above nearly everything, and pulling its descendants in would
        # report every blank-node Rendition in a good package.
        reach = ctx.typed_as if ctx.ontology.requires_an_iri(cls) else ctx.typed_exactly
        for subject in reach(cls):
            if not is_named(subject):
                yield Violation("instances of %s must have an absolute IRI" % class_name,
                                subject=ctx.ref(subject))
    return check


def _not_used_directly(prefix: str, class_name: str):
    """An abstract grouping class: type instances as one of its subclasses."""
    cls = NAMESPACES[prefix][class_name]

    def check(ctx):
        for subject in ctx.graph.subjects(RDF.type, cls):
            yield Violation("%s is not intended to be used directly; "
                            "use one of its subclasses" % class_name,
                            subject=ctx.ref(subject))
    return check


#: The remedy is the same shape for all sixty-one, because the defect is: the
#: element was written without an identifier, so nothing else in the package —
#: or in the package that references this one — can point at it.
NAMED_FIX = ('Give the <%(prefix)s:%(cls)s> element an rdf:about with an IRI, for example '
             'rdf:about="urn:uuid:..." or a URL under a domain you control. Without '
             'one the element is anonymous, so no other statement can refer to it '
             'and a consumer merging this package with another cannot tell two of '
             'them apart.')

ABSTRACT_FIX = ('Retype the instance as one of the subclasses of %(prefix)s:%(cls)s. The '
                'grouping class says only that something of that family is involved, '
                'which leaves a consumer nothing to act on.')


#: Rules whose class the catalogue dates earlier than the vocabulary does.
#:
#: `tools/version_inventory.py` compares each rule's declared versions against
#: the terms that version's ontology actually carried. M97.1/2 name
#: iirds:ClassificationDomain, which arrives in 1.2 with the external
#: classification vocabulary; M49 names iirds:IdentityType and M76
#: mch:ProtectiveEquipment, both of which arrive in 1.1 — settled against the
#: Consortium's own published schemas for every edition, 1.0 included. A rule cannot apply before the class it is about exists.
NARROWED = {
    "M49":   ("1.1", "1.2", "1.3"),
    "M76":   ("1.1", "1.2", "1.3"),
    "M97.1": ("1.2", "1.3"),
    "M97.2": ("1.2", "1.3"),
}


def _register() -> None:
    for rule_id, prefix, class_name, requirement in MUST_HAVE_IRI:
        fn = _must_have_iri(prefix, class_name)
        fn.__name__ = "%s_%s_must_have_iri" % (rule_id.replace(".", "_").lower(), class_name.lower())
        # Always the generated sentence, never the catalogue cell. The cells
        # are either the bare table fragment "IRI: REQUIRED" or -- for
        # M78-M94 -- the ontology's own description prose ("Not intended to
        # be used directly..."), which as a message tells the reader about a
        # different rule than the one firing, and as shipped text contradicts
        # every "no ontology content" notice in shapes/. The constraint is
        # identical for every row, so one accurate sentence covers them all.
        rule(rule_id, versions=NARROWED.get(rule_id),
             covers=(requirement,) if requirement else (),
             title="instances of %s must have an IRI" % class_name,
             fix=NAMED_FIX % {"prefix": PREFIXES[prefix], "cls": class_name})(fn)

    for rule_id, prefix, class_name in NOT_USED_DIRECTLY:
        fn = _not_used_directly(prefix, class_name)
        fn.__name__ = "%s_%s_not_direct" % (rule_id.replace(".", "_").lower(), class_name.lower())
        rule(rule_id, fix=ABSTRACT_FIX % {"prefix": PREFIXES[prefix],
                                          "cls": class_name})(fn)


_register()
'''


def sort_key(rule_id: str):
    head = rule_id[0]
    rest = rule_id[1:]
    parts = rest.split(".")
    out = []
    for part in parts:
        digits = "".join(c for c in part if c.isdigit())
        out.append((int(digits) if digits else 0, part))
    return (head, out)


def collect(ontology):
    tables = {"MUST_HAVE_IRI": [], "NOT_USED_DIRECTLY": []}
    skipped = []

    for rule_id, meta in CATALOG.items():
        family = FAMILIES.get((meta.get("category") or "").strip().lower())
        if family is None:
            continue
        path = (meta.get("path") or "").strip()
        if not path or "," in path or " " in path:
            skipped.append((rule_id, path, "path is not a single class name"))
            continue
        found = [(prefix, ns[path]) for prefix, ns in NAMESPACES
                 if (ns[path], RDF.type, RDFS.Class) in ontology.graph]
        if not found:
            skipped.append((rule_id, path, "not a class in any bundled ontology"))
            continue
        if len(found) > 1:
            skipped.append((rule_id, path, "ambiguous: defined in %s"
                            % ", ".join(p for p, _ in found)))
            continue
        prefix, _iri = found[0]
        tables[family].append((rule_id, prefix, path))

    for rows in tables.values():
        rows.sort(key=lambda row: sort_key(row[0]))
    _attach_appendix_rows(tables["MUST_HAVE_IRI"])
    return tables, skipped


#: prefix in this table -> the word appendix A's ids use for the same domain.
DOMAIN = {"IIRDS": "core", "HOV": "handover", "MACH": "machinery", "SW": "software"}


def _attach_appendix_rows(rows) -> None:
    """Give each row the appendix A obligation it answers, where that is one.

    The generated rules were written *from* appendix A and never told which of
    its rows they were answering, so eighty-four of the two hundred and eighty
    obligations this project publishes a figure against sat unclaimed while
    fifty of them were being checked. The id carries the class, so the match is
    the class — and where two rules check one class it is not a match but a
    question, left empty here and reported by `tools/appendix_a_map.py`.
    """
    import collections
    import json

    index = json.loads((ROOT / "docs" / "requirements.json").read_text("utf-8"))
    reduced = (set(index["reductions"]["keyword_definition"])
               | set(index["reductions"]["restated_in_the_overview"]))
    by_class = {}
    for row in index["requirements"]:
        if not row.get("absolute") or row["id"] in reduced:
            continue
        if " ".join(row["sentence"].split()) != "IRI: REQUIRED":
            continue
        match = re.match(r"^rdfclasses_(\w+?)_(\w+)#\d+$", row["id"])
        if match:
            by_class[(match.group(1), match.group(2))] = row["id"]

    how_many = collections.Counter(class_name for _id, _p, class_name in rows)
    for i, (rule_id, prefix, class_name) in enumerate(rows):
        requirement = by_class.get((DOMAIN[prefix], class_name))
        rows[i] = (rule_id, prefix, class_name,
                   requirement if requirement and how_many[class_name] == 1 else None)


def render(tables) -> str:
    count = sum(len(rows) for rows in tables.values())
    out = [HEADER.replace("{count}", str(count))]
    for name in ("MUST_HAVE_IRI", "NOT_USED_DIRECTLY"):
        rows = tables[name]
        out.append("#: %d rules.\n%s = [\n" % (len(rows), name))
        width = max((len(r[0]) for r in rows), default=0) + 3
        for row in rows:
            rule_id, prefix, class_name = row[0], row[1], row[2]
            requirement = row[3] if len(row) > 3 else None
            out.append('    (%s %-7s %-34s %r),\n'
                       % (('"%s",' % rule_id).ljust(width), '"%s",' % prefix,
                          "%r," % class_name, requirement))
        out.append("]\n")
    out.append(BODY)
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the file would change")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    tables, skipped = collect(load())
    text = render(tables)

    for rule_id, path, why in sorted(skipped, key=lambda s: sort_key(s[0])):
        print("skipped %-8s path=%-34r %s" % (rule_id, path, why), file=sys.stderr)

    if args.stdout:
        print(text)
        return 0
    if args.check:
        current = OUT.read_text("utf-8") if OUT.exists() else ""
        if current == text:
            print("schema_tables.py is up to date")
            return 0
        print("schema_tables.py is out of date; rerun without --check", file=sys.stderr)
        return 1

    OUT.write_text(text, "utf-8")
    for name, rows in tables.items():
        print("%-18s %3d rules" % (name, len(rows)))
    print("wrote %s" % OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
